spring:
 r2dbc:
  url: r2dbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433}/${DB_NAME:TransporteCargaPesada}?trustServerCertificate=true&encrypt=false
  username: ${DB_USER:usr-desarrollo}
  password: ${DB_PASS:}
  pool:
   enabled: ${DB_POOL_ENABLED:false}

app:
 jwt:
  secret: ${JWT_SECRET:change-me-in-production}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  issuer: ${JWT_ISSUER:genesis-flota-api}

logging:
 level:
  com.genesis.flota: DEBUG
  io.r2dbc.mssql: INFO

server:
 port: ${SERVER_PORT:7136}
